// src/app/calculator/calculator.component.ts
import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-calculator',
  templateUrl: './calculator.component.html',
  styleUrls: ['./calculator.component.scss']
})
export class CalculatorComponent implements OnInit {

  income!: number;
  ipa!: number;
  years!: number;
  monthlyPayment: number;
  maxHousePrice: number;

  constructor() { 
    this.monthlyPayment = 0.0;
    this.maxHousePrice = 0.0;
  }

  ngOnInit(): void {
  }

  calculateMortgage(): void {
    console.log(this.income);
    console.log(this.ipa);
    console.log(this.years);
  }

}

<section class="section calculator">
  <div class="container">
    <div class="field">
      <label class="label">Ingresos netos mensuales:</label>
      <div class="control">
        <input
          class="input"
          type="number"
          placeholder="1500"
          min="0"
          [(ngModel)]="income"
        />
      </div>
      <p>
        ¿No conoces tus ingresos netos?
        <a
          href="https://cincodias.elpais.com/herramientas/calculadora-sueldo-neto/"
          target="blank"
          >Calcúlalos gratis aquí</a
        >
      </p>
    </div>
    <div class="field">
      <label class="label">Intereses anuales a <em>tipo fijo</em> (TIN):</label>
      <div class="control">
        <input
          class="input"
          type="number"
          placeholder="2.0"
          min="0"
          [(ngModel)]="ipa"
        />
      </div>
      <p>
        ¿No tienes claro el TIN?
        <a
          href="https://www.idealista.com/hipotecas/comparador-hipotecas/"
          target="blank"
          >Empieza buscando ofertas aquí</a
        >
      </p>
    </div>
    <div class="field">
      <label class="label">Años:</label>
      <div class="control">
        <input
          class="input"
          type="number"
          placeholder="30"
          min="0"
          [(ngModel)]="years"
        />
      </div>
      <p>A más años pagarás más intereses</p>
    </div>
    <div class="columns">
      <div class="column is-10">
        <a
          class="button is-medium is-fullwidth is-primary"
          (click)="calculateMortgage()"
          >Calcular</a
        >
      </div>
      <div class="column is-2">
        <a class="button is-medium is-fullwidth is-info is-outlined">Borrar</a>
      </div>
    </div>
  </div>
  <div class="section container">
    <div class="content is-large">
      <ul>
        <li>
          La cuota mensual máxima que te puedes permitir es:
          <strong>{{ income ? income * 0.3 : 0 }} euros</strong>. La cuota máxima es un 30% de tus ingresos netos.
        </li>
        <li>
          El precio máximo de la vivienda que puedes permitirte es:
          <strong> {{ maxHousePrice }} euros</strong>. El banco solo te prestará el 80% de esta cantidad.
        </li>
      </ul>
    </div>
  </div>
</section>

// src/components/calculator.vue
<template lang="html">
  <section class="section calculator">
    <div class="container">
      <div class="field">
        <label class="label">Ingresos netos mensuales:</label>
        <div class="control">
          <input
            class="input"
            type="number"
            placeholder="1800"
            min="0"
            v-on:focusout="updateIncome"
            v-model="income"
          />
        </div>
        <p>¿No conoces tus ingresos netos? Calcúlalos aquí</p>
      </div>
    </div>
    <div class="section container">
      <div class="content is-large">
        <ul>
          <li>
            La cuota mensual máxima que te puedes permitir es:
            <strong>{{ income ? income * 0.3 : 0 }} euros</strong>
          </li>
          <li>
            El precio máximo de la vivienda que puedes permitirte es:
            <strong> {{ price }} euros</strong>
          </li>
        </ul>
      </div>
    </div>
  </section>
</template>

<script lang="js">

  export default  {
    name: 'Calculator',
    props: [],
    created () {
    },
    data () {
      return {
        price: 0
      }
    },
    methods: {
      updateIncome() {
        this.price = this.income * 0.30 * 360;
        this.calculateMortgatePayment(100000.0, 1.0, 360);
      },
      calculateMortgatePayment(amount, ipa, n) {
        const i = ipa / 12;
        const a = (1-((1+i) ** (-n))) / i;
        console.log(a)
        const payments = amount / a;
        console.log(payments);
      }
    },
    computed: {

    }
}
</script>
